### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by kgryte** [compute-io/anagram-hash#1]
Take a look and see if everything makes sense and/or needs refactoring/rethinking. Thanks!

**Comment by kgryte** [comment]
Note: builds are currently breaking on Node v0.8 due to a [bug](https://github.com/iarna/are-we-there-yet/issues/1) in a dependency. Waiting for the [fix](https://github.com/iarna/are-we-there-yet/pull/2) to land.

**Comment by Planeshifter** [comment]
LGTM.

**Comment by kgryte** [comment]
Awesome. Thanks!
